### ISSUE TITLE
Implement method for regenerating 2FA otp. 

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Spoon#71]

**Comment by Sweta271097** [comment]
@Tjoosten Can I know more about this issue?

**Comment by Tjoosten** [comment]
Sure! 

To begin with for now 2Fa is emplemented in this starter template. But when a user has en,abled his 2fa, And he thinks someone is also using his 2fa one time pass token. He needs to be able to regenerate his token. 

If you have other questions. Feel free to ask them.
